/* Generated By:JavaCC: Do not edit this line. QParJavaParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QParJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int LSQPAREN = 9;
  /** RegularExpression Id. */
  int RSQPAREN = 10;
  /** RegularExpression Id. */
  int LBRACE = 11;
  /** RegularExpression Id. */
  int RBRACE = 12;
  /** RegularExpression Id. */
  int SEMICOLON = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int DOT = 15;
  /** RegularExpression Id. */
  int ASSIGN = 16;
  /** RegularExpression Id. */
  int LT = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int AND = 20;
  /** RegularExpression Id. */
  int NOT = 21;
  /** RegularExpression Id. */
  int BOOLEAN = 22;
  /** RegularExpression Id. */
  int CLASS = 23;
  /** RegularExpression Id. */
  int INTERFACE = 24;
  /** RegularExpression Id. */
  int ELSE = 25;
  /** RegularExpression Id. */
  int EXTENDS = 26;
  /** RegularExpression Id. */
  int FALSE = 27;
  /** RegularExpression Id. */
  int IF = 28;
  /** RegularExpression Id. */
  int WHILE = 29;
  /** RegularExpression Id. */
  int SYNCH = 30;
  /** RegularExpression Id. */
  int FOR = 31;
  /** RegularExpression Id. */
  int INTEGER = 32;
  /** RegularExpression Id. */
  int LENGTH = 33;
  /** RegularExpression Id. */
  int MAIN = 34;
  /** RegularExpression Id. */
  int NEW = 35;
  /** RegularExpression Id. */
  int PUBLIC = 36;
  /** RegularExpression Id. */
  int STATIC = 37;
  /** RegularExpression Id. */
  int STRING = 38;
  /** RegularExpression Id. */
  int THIS = 39;
  /** RegularExpression Id. */
  int TRUE = 40;
  /** RegularExpression Id. */
  int PRINT = 41;
  /** RegularExpression Id. */
  int VOID = 42;
  /** RegularExpression Id. */
  int SCOMMENT1 = 43;
  /** RegularExpression Id. */
  int SCOMMENT2 = 44;
  /** RegularExpression Id. */
  int MHP = 45;
  /** RegularExpression Id. */
  int START = 46;
  /** RegularExpression Id. */
  int WAIT = 47;
  /** RegularExpression Id. */
  int NOTIFY = 48;
  /** RegularExpression Id. */
  int NOTIFYALL = 49;
  /** RegularExpression Id. */
  int JOIN = 50;
  /** RegularExpression Id. */
  int RUN = 51;
  /** RegularExpression Id. */
  int THREAD = 52;
  /** RegularExpression Id. */
  int TRY = 53;
  /** RegularExpression Id. */
  int CATCH = 54;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 55;
  /** RegularExpression Id. */
  int IDENTIFIER = 56;
  /** RegularExpression Id. */
  int LETTER = 57;
  /** RegularExpression Id. */
  int DIGIT = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":\"",
    "\".\"",
    "\"=\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"&&\"",
    "\"!\"",
    "\"boolean\"",
    "\"class\"",
    "\"interface\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"if\"",
    "\"while\"",
    "\"synchronized\"",
    "\"for\"",
    "\"int\"",
    "\"length\"",
    "\"main\"",
    "\"new\"",
    "\"public\"",
    "\"static\"",
    "\"String\"",
    "\"this\"",
    "\"true\"",
    "\"System.out.println\"",
    "\"void\"",
    "\"/*\"",
    "\"*/\"",
    "\"mhp?\"",
    "\"start\"",
    "\"wait\"",
    "\"notify\"",
    "\"notifyAll\"",
    "\"join\"",
    "\"run\"",
    "\"Thread\"",
    "\"try\"",
    "\"catch\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"*\"",
  };

}
